# Generated by Django 3.1.4 on 2020-12-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date sent')),
            ],
        ),
    ]
