# Generated by Django 3.1.4 on 2020-12-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='path',
        ),
        migrations.RemoveField(
            model_name='request',
            name='type',
        ),
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.CharField(default='description', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='params',
            field=models.CharField(default='params', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='status', max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='status_code',
            field=models.IntegerField(default=0),
        ),
    ]
