# Generated by Django 3.1.4 on 2020-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_editor', '0002_auto_20201208_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
